# Generated by Django 3.0.7 on 2021-01-10 15:04

from django.db import migrations, models
import django.utils.timezone
import wayr_apis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('username', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='mobilenumber')),
                ('otp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=12, verbose_name='mobilenumber')),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('tripID', models.AutoField(primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=80)),
                ('clientContact', models.CharField(max_length=80)),
                ('clientSource', models.CharField(max_length=80)),
                ('clientDestination', models.CharField(blank=True, default='', max_length=80)),
                ('clientPrice', models.CharField(default='500', max_length=80)),
                ('clientCar', models.CharField(default=wayr_apis.models.getDefaultCar, max_length=20)),
                ('clientCarModel', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='mobile')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address')),
                ('password', models.CharField(default='ThisIsRootPassword', max_length=255)),
                ('role', models.CharField(default=wayr_apis.models.getDefaultRole, max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('pan', models.CharField(default='', max_length=255)),
                ('panfile', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
