# Generated by Django 3.0.7 on 2021-01-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayr_apis', '0002_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('licenseno', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=12, verbose_name='mobilenumber')),
                ('aadharno', models.CharField(default='', max_length=25)),
                ('licensefile', models.CharField(default='', max_length=25)),
                ('aadharfile', models.CharField(default='', max_length=25)),
                ('name', models.CharField(default='', max_length=25)),
                ('pancard', models.CharField(default='', max_length=25)),
                ('nickname', models.CharField(default='', max_length=25)),
                ('photourl', models.CharField(default='', max_length=25)),
                ('number', models.CharField(default='', max_length=25)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
