# Generated by Django 3.0.7 on 2021-01-15 10:55

from django.db import migrations, models
import wayr_apis.models


class Migration(migrations.Migration):

    dependencies = [
        ('wayr_apis', '0003_drivers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('rcnumber', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vtype', models.CharField(default=wayr_apis.models.getDefaultCar, max_length=20)),
                ('model', models.CharField(default='', max_length=40)),
                ('insuranceno', models.CharField(default='', max_length=40)),
                ('permitno', models.CharField(default='', max_length=40)),
                ('permitdate', models.CharField(default='99991231', max_length=8, verbose_name='insurace date')),
                ('insdate', models.CharField(default='', max_length=40, verbose_name='insurance date')),
                ('nickname', models.CharField(default='', max_length=40)),
                ('photo', models.CharField(default='', max_length=40)),
                ('nameofrc', models.CharField(default='', max_length=40, verbose_name='nameofrc')),
                ('isActive', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=12, verbose_name='mobilenumber')),
            ],
        ),
    ]
