# Generated by Django 3.0.7 on 2021-01-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayr_apis', '0004_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='clientCarModel',
            new_name='carModel',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='clientCar',
            new_name='cartype',
        ),
        migrations.AddField(
            model_name='trips',
            name='date',
            field=models.CharField(default='20210115', max_length=8, verbose_name='trip date'),
        ),
        migrations.AddField(
            model_name='trips',
            name='driver',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trips',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='time',
            field=models.CharField(default='16:54', max_length=6, verbose_name='trip time'),
        ),
        migrations.AddField(
            model_name='trips',
            name='vehicle',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trips',
            name='vendor',
            field=models.CharField(default='', max_length=12, verbose_name='mobilenumber'),
            preserve_default=False,
        ),
    ]
