# Generated by Django 3.0.7 on 2021-01-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayr_apis', '0005_auto_20210115_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='time',
            field=models.CharField(default='16:55', max_length=6, verbose_name='trip time'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='vendor',
            field=models.CharField(default='', max_length=12, verbose_name='mobilenumber'),
        ),
    ]
